/* Generated by Yosys 0.38+37 (git sha1 42920c9bc, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module AND2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  AND2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module AND2X2(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  AND2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module AOI21X1(A, B, C, Y);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
  AOI21X1 _0_ (
    .A(A),
    .B(B),
    .C(C),
    .Y(Y)
  );
endmodule

module AOI22X1(A, B, C, D, Y);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
  AOI22X1 _0_ (
    .A(A),
    .B(B),
    .C(C),
    .D(D),
    .Y(Y)
  );
endmodule

module BUFX2(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  assign Y = A;
endmodule

module BUFX4(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  assign Y = A;
endmodule

module CLKBUF1(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  assign Y = A;
endmodule

module CLKBUF2(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  assign Y = A;
endmodule

module CLKBUF3(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  assign Y = A;
endmodule

module DFFNEGX1(CLK, D, Q);
  input CLK;
  wire CLK;
  input D;
  wire D;
  wire DS0000;
  output Q;
  wire Q;
  DFFNEGX1 _0_ (
    .CLK(CLK),
    .D(D),
    .Q(DS0000)
  );
  assign Q = DS0000;
endmodule

module DFFPOSX1(CLK, D, Q);
  input CLK;
  wire CLK;
  input D;
  wire D;
  wire DS0000;
  output Q;
  wire Q;
  DFFPOSX1 _0_ (
    .CLK(CLK),
    .D(D),
    .Q(DS0000)
  );
  assign Q = DS0000;
endmodule

module DFFSR(CLK, D, Q, R, S);
  input CLK;
  wire CLK;
  input D;
  wire D;
  wire P0002;
  output Q;
  wire Q;
  input R;
  wire R;
  input S;
  wire S;
  DFFSR _0_ (
    .CLK(CLK),
    .D(D),
    .Q(P0002),
    .R(R),
    .S(S)
  );
  assign Q = P0002;
endmodule

module FAX1(A, B, C, YC, YS);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output YC;
  wire YC;
  output YS;
  wire YS;
  wire _0_;
  wire _1_;
  wire _2_;
  NAND2X1 _3_ (
    .A(A),
    .B(C),
    .Y(_0_)
  );
  XNOR2X1 _4_ (
    .A(A),
    .B(C),
    .Y(_1_)
  );
  XNOR2X1 _5_ (
    .A(B),
    .B(_1_),
    .Y(YS)
  );
  OAI21X1 _6_ (
    .A(A),
    .B(C),
    .C(B),
    .Y(_2_)
  );
  NAND2X1 _7_ (
    .A(_0_),
    .B(_2_),
    .Y(YC)
  );
endmodule

module HAX1(A, B, YC, YS);
  input A;
  wire A;
  input B;
  wire B;
  output YC;
  wire YC;
  output YS;
  wire YS;
  AND2X1 _0_ (
    .A(A),
    .B(B),
    .Y(YC)
  );
  XOR2X1 _1_ (
    .A(A),
    .B(B),
    .Y(YS)
  );
endmodule

module INVX1(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  INVX1 _0_ (
    .A(A),
    .Y(Y)
  );
endmodule

module INVX2(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  INVX1 _0_ (
    .A(A),
    .Y(Y)
  );
endmodule

module INVX4(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  INVX1 _0_ (
    .A(A),
    .Y(Y)
  );
endmodule

module INVX8(A, Y);
  input A;
  wire A;
  output Y;
  wire Y;
  INVX1 _0_ (
    .A(A),
    .Y(Y)
  );
endmodule

module LATCH(CLK, D, Q);
  input CLK;
  wire CLK;
  input D;
  wire D;
  wire DS0000;
  output Q;
  wire Q;
  \$_DLATCH_P_  _0_ (
    .D(D),
    .E(CLK),
    .Q(DS0000)
  );
  assign Q = DS0000;
endmodule

module MUX2X1(A, B, S, Y);
  input A;
  wire A;
  input B;
  wire B;
  input S;
  wire S;
  output Y;
  wire Y;
  MUX2X1 _0_ (
    .A(A),
    .B(B),
    .S(S),
    .Y(Y)
  );
endmodule

module NAND2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  NAND2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module NAND3X1(A, B, C, Y);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
  NAND3X1 _0_ (
    .A(A),
    .B(B),
    .C(C),
    .Y(Y)
  );
endmodule

module NOR2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  NOR2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module NOR3X1(A, B, C, Y);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
  NOR3X1 _0_ (
    .A(A),
    .B(B),
    .C(C),
    .Y(Y)
  );
endmodule

module OAI21X1(A, B, C, Y);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  output Y;
  wire Y;
  OAI21X1 _0_ (
    .A(A),
    .B(B),
    .C(C),
    .Y(Y)
  );
endmodule

module OAI22X1(A, B, C, D, Y);
  input A;
  wire A;
  input B;
  wire B;
  input C;
  wire C;
  input D;
  wire D;
  output Y;
  wire Y;
  OAI22X1 _0_ (
    .A(A),
    .B(B),
    .C(C),
    .D(D),
    .Y(Y)
  );
endmodule

module OR2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  OR2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module OR2X2(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  OR2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module TBUFX1(A, EN, Y);
  input A;
  wire A;
  input EN;
  wire EN;
  output Y;
  wire Y;
  INVX1 _0_ (
    .A(A),
    .Y(Y)
  );
endmodule

module TBUFX2(A, EN, Y);
  input A;
  wire A;
  input EN;
  wire EN;
  output Y;
  wire Y;
  INVX1 _0_ (
    .A(A),
    .Y(Y)
  );
endmodule

module XNOR2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  XNOR2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module XOR2X1(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  XOR2X1 _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

module tx_uart(clk, rst_n, start, data, rs232_tx, done_tx);
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  wire [3:0] bit_cnt;
  input clk;
  wire clk;
  input [7:0] data;
  wire [7:0] data;
  output done_tx;
  wire done_tx;
  output rs232_tx;
  wire rs232_tx;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  INVX1 _33_ (
    .A(bit_cnt[3]),
    .Y(_4_)
  );
  INVX1 _34_ (
    .A(bit_cnt[0]),
    .Y(_5_)
  );
  INVX1 _35_ (
    .A(bit_cnt[1]),
    .Y(_6_)
  );
  INVX1 _36_ (
    .A(rst_n),
    .Y(_7_)
  );
  INVX1 _37_ (
    .A(data[7]),
    .Y(_8_)
  );
  INVX1 _38_ (
    .A(data[3]),
    .Y(_9_)
  );
  NAND2X1 _39_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_10_)
  );
  NOR2X1 _40_ (
    .A(bit_cnt[3]),
    .B(_10_),
    .Y(_11_)
  );
  OAI21X1 _41_ (
    .A(bit_cnt[2]),
    .B(_11_),
    .C(_7_),
    .Y(_12_)
  );
  AOI21X1 _42_ (
    .A(bit_cnt[2]),
    .B(_11_),
    .C(_12_),
    .Y(_0_)
  );
  OAI21X1 _43_ (
    .A(_4_),
    .B(bit_cnt[1]),
    .C(_7_),
    .Y(_13_)
  );
  NAND2X1 _44_ (
    .A(_5_),
    .B(_6_),
    .Y(_14_)
  );
  OAI21X1 _45_ (
    .A(bit_cnt[3]),
    .B(_10_),
    .C(_14_),
    .Y(_15_)
  );
  NOR2X1 _46_ (
    .A(_13_),
    .B(_15_),
    .Y(_1_)
  );
  OAI21X1 _47_ (
    .A(bit_cnt[2]),
    .B(_14_),
    .C(bit_cnt[3]),
    .Y(_16_)
  );
  NAND2X1 _48_ (
    .A(bit_cnt[0]),
    .B(_6_),
    .Y(_17_)
  );
  OR2X1 _49_ (
    .A(_4_),
    .B(bit_cnt[2]),
    .Y(_18_)
  );
  NOR2X1 _50_ (
    .A(_17_),
    .B(_18_),
    .Y(done_tx)
  );
  OAI21X1 _51_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[2]),
    .C(bit_cnt[3]),
    .Y(_19_)
  );
  OAI21X1 _52_ (
    .A(bit_cnt[0]),
    .B(_16_),
    .C(_7_),
    .Y(_20_)
  );
  AOI21X1 _53_ (
    .A(bit_cnt[0]),
    .B(_19_),
    .C(_20_),
    .Y(_2_)
  );
  OAI21X1 _54_ (
    .A(_9_),
    .B(_14_),
    .C(bit_cnt[2]),
    .Y(_21_)
  );
  NAND3X1 _55_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(data[6]),
    .Y(_22_)
  );
  NAND3X1 _56_ (
    .A(_5_),
    .B(bit_cnt[1]),
    .C(data[5]),
    .Y(_23_)
  );
  NAND3X1 _57_ (
    .A(bit_cnt[0]),
    .B(_6_),
    .C(data[4]),
    .Y(_24_)
  );
  NAND3X1 _58_ (
    .A(_22_),
    .B(_23_),
    .C(_24_),
    .Y(_25_)
  );
  NAND3X1 _59_ (
    .A(_5_),
    .B(bit_cnt[1]),
    .C(data[1]),
    .Y(_26_)
  );
  NAND3X1 _60_ (
    .A(bit_cnt[0]),
    .B(_6_),
    .C(data[0]),
    .Y(_27_)
  );
  NAND3X1 _61_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(data[2]),
    .Y(_28_)
  );
  NAND3X1 _62_ (
    .A(_26_),
    .B(_27_),
    .C(_28_),
    .Y(_29_)
  );
  OAI22X1 _63_ (
    .A(_21_),
    .B(_25_),
    .C(_29_),
    .D(bit_cnt[2]),
    .Y(_30_)
  );
  NOR2X1 _64_ (
    .A(_14_),
    .B(_18_),
    .Y(_31_)
  );
  AOI22X1 _65_ (
    .A(_4_),
    .B(_30_),
    .C(_31_),
    .D(_8_),
    .Y(rs232_tx)
  );
  AOI21X1 _66_ (
    .A(bit_cnt[2]),
    .B(_11_),
    .C(_31_),
    .Y(_32_)
  );
  AOI21X1 _67_ (
    .A(_19_),
    .B(_32_),
    .C(rst_n),
    .Y(_3_)
  );
  DFFPOSX1 _68_ (
    .CLK(clk),
    .D(_2_),
    .Q(bit_cnt[0])
  );
  DFFPOSX1 _69_ (
    .CLK(clk),
    .D(_1_),
    .Q(bit_cnt[1])
  );
  DFFPOSX1 _70_ (
    .CLK(clk),
    .D(_0_),
    .Q(bit_cnt[2])
  );
  DFFPOSX1 _71_ (
    .CLK(clk),
    .D(_3_),
    .Q(bit_cnt[3])
  );
endmodule
