/* Generated by Yosys 0.38+37 (git sha1 42920c9bc, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module tx_uart(clk, rst_n, start, data, rs232_tx, done_tx);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire [7:0] _39_;
  wire [3:0] bit_cnt;
  input clk;
  wire clk;
  input [7:0] data;
  wire [7:0] data;
  output done_tx;
  wire done_tx;
  output rs232_tx;
  wire rs232_tx;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  NOR4_X1 _40_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[3]),
    .A3(_02_),
    .A4(_01_),
    .ZN(_07_)
  );
  NOR4_X1 _41_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .A3(bit_cnt[3]),
    .A4(_01_),
    .ZN(_08_)
  );
  NOR4_X1 _42_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[2]),
    .A3(bit_cnt[3]),
    .A4(_02_),
    .ZN(_09_)
  );
  NOR4_X1 _43_ (
    .A1(bit_cnt[1]),
    .A2(bit_cnt[3]),
    .A3(_01_),
    .A4(_39_[4]),
    .ZN(_10_)
  );
  NOR4_X1 _44_ (
    .A1(_07_),
    .A2(_08_),
    .A3(_09_),
    .A4(_10_),
    .ZN(_11_)
  );
  NOR4_X1 _45_ (
    .A1(bit_cnt[2]),
    .A2(bit_cnt[3]),
    .A3(_02_),
    .A4(_39_[4]),
    .ZN(_12_)
  );
  NOR4_X1 _46_ (
    .A1(bit_cnt[1]),
    .A2(bit_cnt[2]),
    .A3(bit_cnt[3]),
    .A4(_39_[4]),
    .ZN(_13_)
  );
  NOR4_X1 _47_ (
    .A1(bit_cnt[3]),
    .A2(_02_),
    .A3(_01_),
    .A4(_39_[4]),
    .ZN(_14_)
  );
  NOR4_X1 _48_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .A3(bit_cnt[2]),
    .A4(_00_),
    .ZN(_15_)
  );
  NOR4_X1 _49_ (
    .A1(_12_),
    .A2(_13_),
    .A3(_14_),
    .A4(_15_),
    .ZN(_16_)
  );
  AND2_X1 _50_ (
    .A1(_11_),
    .A2(_16_),
    .ZN(_17_)
  );
  NAND2_X1 _51_ (
    .A1(_11_),
    .A2(_16_),
    .ZN(_18_)
  );
  OR4_X1 _52_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .A3(bit_cnt[2]),
    .A4(bit_cnt[3]),
    .ZN(_19_)
  );
  NAND3_X1 _53_ (
    .A1(_11_),
    .A2(_16_),
    .A3(_19_),
    .ZN(_20_)
  );
  OR4_X1 _54_ (
    .A1(bit_cnt[1]),
    .A2(bit_cnt[2]),
    .A3(_39_[4]),
    .A4(_00_),
    .ZN(_21_)
  );
  INV_X1 _55_ (
    .A(_21_),
    .ZN(_37_)
  );
  NAND3_X1 _56_ (
    .A1(bit_cnt[0]),
    .A2(_17_),
    .A3(_21_),
    .ZN(_22_)
  );
  NAND2_X1 _57_ (
    .A1(_39_[4]),
    .A2(_20_),
    .ZN(_23_)
  );
  AOI21_X1 _58_ (
    .A(rst_n),
    .B1(_22_),
    .B2(_23_),
    .ZN(_03_)
  );
  NAND2_X1 _59_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .ZN(_24_)
  );
  AOI21_X1 _60_ (
    .A(_24_),
    .B1(_16_),
    .B2(_11_),
    .ZN(_25_)
  );
  AOI21_X1 _61_ (
    .A(bit_cnt[1]),
    .B1(_18_),
    .B2(bit_cnt[0]),
    .ZN(_26_)
  );
  NOR3_X1 _62_ (
    .A1(rst_n),
    .A2(_25_),
    .A3(_26_),
    .ZN(_04_)
  );
  XNOR2_X1 _63_ (
    .A(bit_cnt[2]),
    .B(_25_),
    .ZN(_27_)
  );
  NAND3_X1 _64_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .A3(bit_cnt[2]),
    .ZN(_28_)
  );
  NOR2_X1 _65_ (
    .A1(rst_n),
    .A2(_27_),
    .ZN(_05_)
  );
  NAND3_X1 _66_ (
    .A1(bit_cnt[3]),
    .A2(_17_),
    .A3(_21_),
    .ZN(_29_)
  );
  XNOR2_X1 _67_ (
    .A(bit_cnt[3]),
    .B(_28_),
    .ZN(_30_)
  );
  NAND2_X1 _68_ (
    .A1(_20_),
    .A2(_30_),
    .ZN(_31_)
  );
  AOI21_X1 _69_ (
    .A(rst_n),
    .B1(_29_),
    .B2(_31_),
    .ZN(_06_)
  );
  AOI22_X1 _70_ (
    .A1(data[4]),
    .A2(_10_),
    .B1(_12_),
    .B2(data[2]),
    .ZN(_32_)
  );
  AOI22_X1 _71_ (
    .A1(data[3]),
    .A2(_08_),
    .B1(_13_),
    .B2(data[0]),
    .ZN(_33_)
  );
  AND2_X1 _72_ (
    .A1(_32_),
    .A2(_33_),
    .ZN(_34_)
  );
  AOI22_X1 _73_ (
    .A1(data[5]),
    .A2(_07_),
    .B1(_15_),
    .B2(data[7]),
    .ZN(_35_)
  );
  AOI22_X1 _74_ (
    .A1(data[1]),
    .A2(_09_),
    .B1(_14_),
    .B2(data[6]),
    .ZN(_36_)
  );
  NAND4_X1 _75_ (
    .A1(_20_),
    .A2(_34_),
    .A3(_35_),
    .A4(_36_),
    .ZN(_38_)
  );
  DFF_X1 _76_ (
    .CK(clk),
    .D(_03_),
    .Q(bit_cnt[0]),
    .QN(_39_[4])
  );
  DFF_X1 _77_ (
    .CK(clk),
    .D(_04_),
    .Q(bit_cnt[1]),
    .QN(_02_)
  );
  DFF_X1 _78_ (
    .CK(clk),
    .D(_05_),
    .Q(bit_cnt[2]),
    .QN(_01_)
  );
  DFF_X1 _79_ (
    .CK(clk),
    .D(_06_),
    .Q(bit_cnt[3]),
    .QN(_00_)
  );
  BUF_X2 _80_ (
    .A(_37_),
    .Z(done_tx)
  );
  BUF_X2 _81_ (
    .A(_38_),
    .Z(rs232_tx)
  );
  assign _39_[3:0] = 4'h0;
endmodule
